# Grafana 配置文件

[default]
instance_name = power-grid-warehouse

[paths]
data = /opt/data/grafana
logs = /opt/logs
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning

[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3000
domain = localhost
root_url = http://localhost:3000/

[database]
type = sqlite3
path = /opt/data/grafana/grafana.db

[session]
provider = file
provider_config = /opt/data/grafana/sessions

[security]
admin_user = admin
admin_password = admin
secret_key = SW2YcwTIb9zpOOhoPsMm
disable_gravatar = true

[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = true
auto_assign_org_role = Viewer

[auth.anonymous]
enabled = false

[log]
mode = file
level = info
format = text

[log.file]
log_rotate = true
max_lines = 1000000
max_size_shift = 28
daily_rotate = true
max_days = 7

[alerting]
enabled = true
execute_alerts = true

[metrics]
enabled = true
interval_seconds = 10

[tracing.jaeger]
address = localhost:14268
always_included_tag = tag1:value1

[snapshots]
external_enabled = false